version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: hiresmart-backend
        container_name: hiresmart-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - hiresmart-network
        depends_on:
            - db
            - redis

    webserver:
        image: nginx:alpine
        container_name: hiresmart-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - hiresmart-network
        depends_on:
            - app

    db:
        image: postgres:15-alpine
        container_name: hiresmart-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-hiresmart}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - hiresmart-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: hiresmart-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - hiresmart-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    hiresmart-network:
        driver: bridge

volumes:
    postgres-data:
    redis-data:
